[project]
name = "bakr"
version = "0.1.0"
description = "Backup file restore tool with drag-and-drop support"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "nicegui>=1.4.0"
]

[project.optional-dependencies]
gui-alternatives = [
    "dearpygui>=1.11.0",
    "tkinterdnd2>=0.3.0"
]
dev = [
    "pytest>=7.0.0",
    "black>=22.0.0",
    "mypy>=1.0.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

