[project]
name = "bakr"
version = "0.1.0"
description = "Backup file restore tool with drag-and-drop support"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "loguru>=0.7.3",
    "plotly>=6.1.1",
    "rich>=14.0.0",
    "streamlit>=1.45.1",
    "textual>=0.72.0",
]

[project.optional-dependencies]
cli = [
    "rich>=13.0.0"
]
dev = [
    "pytest>=7.0.0",
    "black>=22.0.0",
    "mypy>=1.0.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

